/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Brisa API
 * API for the Brisa Invoice Scraper
 * OpenAPI spec version: 1.0.0
 */
import type { CaptchaChallengeMetadata } from './captchaChallengeMetadata';

export interface CaptchaChallenge {
  id: string;
  image: string;
  contentType: string;
  metadata?: CaptchaChallengeMetadata;
}
