/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Brisa API
 * API for the Brisa Invoice Scraper
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from './address';

export interface Issuer {
  name: string;
  cnpj: string;
  trade_name?: string;
  address: Address;
}
