/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Brisa API
 * API for the Brisa Invoice Scraper
 * OpenAPI spec version: 1.0.0
 */
import type { Taxes } from './taxes';

export interface Item {
  line_number: number;
  code?: string;
  description: string;
  quantity: number;
  unit: string;
  unit_price: number;
  total: number;
  taxes?: Taxes;
}
