/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Brisa API
 * API for the Brisa Invoice Scraper
 * OpenAPI spec version: 1.0.0
 */
import type { JobStatus } from './jobStatus';
import type { Receipt } from './receipt';
import type { CaptchaChallenge } from './captchaChallenge';

export interface Job {
  id: string;
  status: JobStatus;
  accessKey: string;
  result?: Receipt;
  error?: string;
  createdAt: string;
  captcha?: CaptchaChallenge;
}
