/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Brisa API
 * API for the Brisa Invoice Scraper
 * OpenAPI spec version: 1.0.0
 */
import type { ReceiptPortal } from './receiptPortal';
import type { Issuer } from './issuer';
import type { Consumer } from './consumer';
import type { Item } from './item';
import type { Taxes } from './taxes';
import type { Payment } from './payment';

export interface Receipt {
  key: string;
  portal: ReceiptPortal;
  issue_date: string;
  receipt_number?: string;
  series?: string;
  issuer: Issuer;
  consumer: Consumer;
  items: Array<Item>;
  /** Value in cents */
  subtotal: number;
  /** Value in cents */
  discount: number;
  /** Value in cents */
  total: number;
  taxes: Taxes;
  payments?: Array<Payment>;
}
