/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Brisa API
 * API for the Brisa Invoice Scraper
 * OpenAPI spec version: 1.0.0
 */

export type SubmitCaptchaBody = {
  solution: string;
};
