/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Brisa API
 * API for the Brisa Invoice Scraper
 * OpenAPI spec version: 1.0.0
 */

import { useMutation, useQuery } from '@tanstack/react-query';
import { customFetch } from '../../lib/custom-fetch';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateInvoiceJobBody, Job, JobId, SubmitCaptchaBody } from '../model';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new invoice scraping job
 */
export const createInvoiceJob = (
  createInvoiceJobBody: CreateInvoiceJobBody,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<JobId>(
    {
      url: `/invoice-jobs`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createInvoiceJobBody,
      signal,
    },
    options,
  );
};

export const getCreateInvoiceJobMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInvoiceJob>>,
    TError,
    { data: CreateInvoiceJobBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInvoiceJob>>,
  TError,
  { data: CreateInvoiceJobBody },
  TContext
> => {
  const mutationKey = ['createInvoiceJob'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInvoiceJob>>, { data: CreateInvoiceJobBody }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return createInvoiceJob(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateInvoiceJobMutationResult = NonNullable<Awaited<ReturnType<typeof createInvoiceJob>>>;
export type CreateInvoiceJobMutationBody = CreateInvoiceJobBody;
export type CreateInvoiceJobMutationError = unknown;

/**
 * @summary Create a new invoice scraping job
 */
export const useCreateInvoiceJob = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createInvoiceJob>>,
      TError,
      { data: CreateInvoiceJobBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createInvoiceJob>>,
  TError,
  { data: CreateInvoiceJobBody },
  TContext
> => {
  const mutationOptions = getCreateInvoiceJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get job status and details
 */
export const getInvoiceJob = (id: string, options?: SecondParameter<typeof customFetch>, signal?: AbortSignal) => {
  return customFetch<Job>({ url: `/invoice-jobs/${id}`, method: 'GET', signal }, options);
};

export const getGetInvoiceJobQueryKey = (id?: string) => {
  return [`/invoice-jobs/${id}`] as const;
};

export const getGetInvoiceJobQueryOptions = <TData = Awaited<ReturnType<typeof getInvoiceJob>>, TError = void>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvoiceJob>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInvoiceJobQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvoiceJob>>> = ({ signal }) =>
    getInvoiceJob(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInvoiceJob>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetInvoiceJobQueryResult = NonNullable<Awaited<ReturnType<typeof getInvoiceJob>>>;
export type GetInvoiceJobQueryError = void;

export function useGetInvoiceJob<TData = Awaited<ReturnType<typeof getInvoiceJob>>, TError = void>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvoiceJob>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvoiceJob>>,
          TError,
          Awaited<ReturnType<typeof getInvoiceJob>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInvoiceJob<TData = Awaited<ReturnType<typeof getInvoiceJob>>, TError = void>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvoiceJob>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvoiceJob>>,
          TError,
          Awaited<ReturnType<typeof getInvoiceJob>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInvoiceJob<TData = Awaited<ReturnType<typeof getInvoiceJob>>, TError = void>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvoiceJob>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get job status and details
 */

export function useGetInvoiceJob<TData = Awaited<ReturnType<typeof getInvoiceJob>>, TError = void>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvoiceJob>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetInvoiceJobQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Submit captcha solution for a job
 */
export const submitCaptcha = (
  id: string,
  submitCaptchaBody: SubmitCaptchaBody,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<void>(
    {
      url: `/invoice-jobs/${id}/captcha`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: submitCaptchaBody,
      signal,
    },
    options,
  );
};

export const getSubmitCaptchaMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitCaptcha>>,
    TError,
    { id: string; data: SubmitCaptchaBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitCaptcha>>,
  TError,
  { id: string; data: SubmitCaptchaBody },
  TContext
> => {
  const mutationKey = ['submitCaptcha'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitCaptcha>>,
    { id: string; data: SubmitCaptchaBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return submitCaptcha(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitCaptchaMutationResult = NonNullable<Awaited<ReturnType<typeof submitCaptcha>>>;
export type SubmitCaptchaMutationBody = SubmitCaptchaBody;
export type SubmitCaptchaMutationError = void;

/**
 * @summary Submit captcha solution for a job
 */
export const useSubmitCaptcha = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitCaptcha>>,
      TError,
      { id: string; data: SubmitCaptchaBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitCaptcha>>,
  TError,
  { id: string; data: SubmitCaptchaBody },
  TContext
> => {
  const mutationOptions = getSubmitCaptchaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
